apiVersion: apps/v1
kind: Deployment
metadata:
    name: subscriber-mgmt-api
    labels:
      app: subscriber-mgmt-api
spec:
    replicas: 2
    selector:
      matchLabels:
        app: subscriber-mgmt-api
    template:
      metadata:
         labels:
            app: subscriber-mgmt-api
      spec:
        containers:
        - name: subscriber-mgmt-api
          image: harig2303/my_repo:subscriber-mgmt-api
          ports:
          - containerPort: 8090